import os
import base64
from io import BytesIO

import streamlit as st
from openai import OpenAI
from PIL import Image

# --- OpenAI 클라이언트 설정 (공백 제거 방어) ---
raw_key = os.getenv("OPENAI_API_KEY") or ""
api_key = raw_key.strip()

client = OpenAI(api_key=api_key)

# --- Streamlit 기본 설정 ---
st.set_page_config(page_title="gpt-image-1 데모", page_icon="🎨")
st.title("🎨 gpt-image-1 이미지 데모")

if not api_key:
    st.error("환경변수 OPENAI_API_KEY가 설정되어 있지 않아요. 터미널에서 export 해주세요.")
    st.stop()

tab_gen, tab_edit = st.tabs(["✨ 텍스트로 새로 생성", "🌀 이미지 변형(편집)"])

# =========================================
# 1️⃣ 텍스트 → 새 이미지 생성
# =========================================
with tab_gen:
    st.subheader("텍스트 프롬프트로 새 이미지 만들기")

    prompt = st.text_area(
        "이미지 프롬프트",
        value="a cute chibi game character holding a glowing sword, anime style",
        height=100,
    )

    col1, col2 = st.columns(2)
    with col1:
        size = st.selectbox(
            "이미지 크기",
            ["auto", "1024x1024", "1024x1536", "1536x1024"],
            index=1,
        )
    with col2:
        quality = st.selectbox(
            "퀄리티",
            ["auto", "low", "medium", "high"],
            index=2,
        )

    if st.button("🖼️ 새 이미지 생성", type="primary"):
        if not prompt.strip():
            st.error("프롬프트를 입력해주세요!")
        else:
            with st.spinner("이미지 생성 중..."):
                try:
                    result = client.images.generate(
                        model="gpt-image-1",
                        prompt=prompt,
                        size=size,
                        quality=quality,
                        n=1,
                    )

                    image_base64 = result.data[0].b64_json
                    image_bytes = base64.b64decode(image_base64)
                    img = Image.open(BytesIO(image_bytes))

                    st.success("이미지 생성 완료!")
                    st.image(img, caption="generated by gpt-image-1", use_column_width=True)
                    st.download_button(
                        "이미지 다운로드 (PNG)",
                        data=image_bytes,
                        file_name="generated_image.png",
                        mime="image/png",
                    )
                except Exception as e:
                    st.error(f"에러 발생: {type(e).__name__} - {e}")

# =========================================
# 2️⃣ 업로드한 이미지 → 변형(편집)
# =========================================
with tab_edit:
    st.subheader("업로드한 이미지를 프롬프트로 변형하기")

    uploaded_file = st.file_uploader(
        "변형하고 싶은 이미지를 업로드하세요 (PNG / JPG / JPEG / WEBP)",
        type=["png", "jpg", "jpeg", "webp"],
    )

    if uploaded_file is not None:
        # 업로드된 이미지를 화면에 미리보기
        bytes_data = uploaded_file.getvalue()
        st.image(bytes_data, caption="원본 이미지", use_column_width=True)

        edit_prompt = st.text_area(
            "이 이미지를 어떻게 바꾸고 싶은지 설명해 주세요",
            value="turn this character into a dark mage with purple flames around them",
            height=100,
        )

        # 선택적으로 input fidelity 같은 옵션을 나중에 추가할 수 있음
        if st.button("🌀 이 이미지 변형하기"):
            if not edit_prompt.strip():
                st.error("변형 프롬프트를 입력해주세요!")
            else:
                with st.spinner("이미지 편집 중..."):
                    try:
                        # 1) 업로드된 바이트 → PIL 이미지로 열기
                        original_img = Image.open(BytesIO(bytes_data)).convert("RGBA")

                        # 2) 다시 PNG로 인메모리 저장
                        img_buffer = BytesIO()
                        original_img.save(img_buffer, format="PNG")
                        img_buffer.seek(0)

                        # 3) 파일 이름(확장자)를 강제로 달아주기 → mimetype 인식용
                        img_buffer.name = "image.png"

                        # 4) gpt-image-1 편집 호출
                        result = client.images.edit(
                            model="gpt-image-1",
                            image=img_buffer,
                            prompt=edit_prompt,
                            # 필요하면 옵션 추가 가능:
                            # size="1024x1024",
                            # quality="high",
                        )

                        image_base64 = result.data[0].b64_json
                        edited_bytes = base64.b64decode(image_base64)
                        edited_img = Image.open(BytesIO(edited_bytes))

                        st.success("이미지 변형 완료!")
                        st.image(
                            edited_img,
                            caption="edited by gpt-image-1",
                            use_column_width=True,
                        )
                        st.download_button(
                            "변형된 이미지 다운로드 (PNG)",
                            data=edited_bytes,
                            file_name="edited_image.png",
                            mime="image/png",
                        )
                    except Exception as e:
                        st.error(f"에러 발생: {type(e).__name__} - {e}")
    else:
        st.info("위에 이미지를 하나 업로드하면, 여기서 프롬프트로 변형할 수 있어요.")
